[package]
name = "changeology"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "changeology"
path = "src/changeology.rs"

[dependencies]
rand = "0.8.5"
buffer-diff = { path = "../diff" }
git = { path = "../git" }
